# Change these first
owner: CS-METIS
repo: metis-dev-status-page

sites:
  - name: Daskhub
    url: https://nb.p3.csgroup.space
  - name: Feature server
    url: https://feature.p3.csgroup.space/
  - name: Grafana
    url: https://grafana.p3.csgroup.space
  - name: Kafka UI
    url: https://kafka.p3.csgroup.space
  - name: Keycloak
    url: https://auth.p3.csgroup.space
  - name: Launcher
    url: https://p3.csgroup.space
  - name: Mattermost
    url: https://chat.p3.csgroup.space
  - name: Pgadmin
    url: https://pgadmin.p3.csgroup.space
  - name: Spring Cloud Dataflow
    url: https://processing.p3.csgroup.space
  - name: Superset
    url: https://superset.p3.csgroup.space
  - name: Topaz
    url: https://topaz.p3.csgroup.space
  - name: Zammad
    url: help.p3.csgroup.space
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.p3.csgroup.space
  # baseUrl: /p2-status-page
  logoUrl: https://p3.csgroup.space/static/images/metis-logo.png
  name: METIS DEV Platform Services status
  introTitle: "This is the uptime monitor and status page for the **METIS DEV Platform**."
  introMessage: If a service doesn't work properly, you may find the reason here. If not, please open an issue.
  navbar:
    - title: Status
      href: /
    - title: Return to platform
      href: https://p3.csgroup.space
  theme: night
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
